version: '3'

services:
  bsc_api:
    build:
      context: api/
      dockerfile: Dockerfile
    container_name: bsc_api
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    env_file:
      - ./.env
    ports:
      - "83:5000"
    expose:
      - 83
    networks:
      - bsc_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 100m

  bsc_demon:
    build:
      context: transactions_demon/
      dockerfile: Dockerfile
    container_name: bsc_demon
    command: /usr/bin/supervisord
    env_file:
      - ./.env
    networks:
      - bsc_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 100m

  bsc_rabbitmq:
    container_name: bsc_rabbitmq
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ./config/docker/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
    networks:
      - bsc_net
    logging:
      options:
        max-size: 100m

  bsc_balancer:
    build:
      context: balancer/
      dockerfile: Dockerfile
    container_name: bsc_balancer
    command: /usr/bin/supervisord
    env_file:
      - ./.env
    networks:
      - bsc_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 100m

networks:
  bsc_net:
    driver: bridge
