version: '3'

services:
  bsc_api:
    restart: always
    build:
      context: api/
      dockerfile: Dockerfile
    container_name: bsc_api
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    env_file:
      - ./.env
    ports:
      - "83:5000"
    expose:
      - 83
    networks:
      - bsc_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 10m

  bsc_demon:
    restart: always
    build:
      context: transactions_demon/
      dockerfile: Dockerfile
    container_name: bsc_demon
    command: /usr/bin/supervisord
    env_file:
      - ./.env
    networks:
      - bsc_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 10m

  bsc_rabbitmq:
    restart: always
    container_name: bsc_rabbitmq
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ./config/docker/rabbitmq:/var/lib/rabbitmq
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
    networks:
      - bsc_net
    logging:
      options:
        max-size: 10m

  bsc_redis:
    container_name: bsc_redis
    image: "bitnami/redis:5.0.4"
    restart: always
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "./config/docker/redis:/bitnami/redis/data"
    networks:
      - bsc_net
    logging:
      options:
        max-size: 10m

  bsc_celery_flower:
    restart: always
    container_name: bsc_celery_flower
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=root
      - AMQP_PASSWORD=password
      - AMQP_ADMIN_USERNAME=root
      - AMQP_ADMIN_PASSWORD=password
      - AMQP_HOST=bsc_rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=bsc_rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"
    expose:
      - 5555
    depends_on:
      - bsc_rabbitmq
      - bsc_redis
    networks:
      - bsc_net
    logging:
      options:
        max-size: 10m

  worker:
    restart: always
    container_name: bsc_balancer_worker
    build:
      context: balancer/
      dockerfile: Dockerfile
    depends_on:
      - bsc_rabbitmq
      - bsc_redis
    env_file:
      - ./.env
    command: celery --app worker.celery_worker worker -l info -Q test-queue -c 1
    networks:
      - bsc_net
    logging:
      options:
        max-size: 10m

  bsc_balancer:
    restart: always
    build:
      context: balancer/
      dockerfile: Dockerfile
    container_name: bsc_balancer
    command: /usr/bin/supervisord
    env_file:
      - ./.env
    networks:
      - bsc_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 10m

networks:
  bsc_net:
    driver: bridge
