version: '3'

services:
  eth_api:
    build:
      context: api/
      dockerfile: Dockerfile
    container_name: eth_api
    command: /usr/bin/supervisord
    env_file:
      - ./.env
    expose:
      - 5000
    networks:
      - eth_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 100m

  eth_demon:
    build:
      context: transactions_demon/
      dockerfile: Dockerfile
    container_name: eth_demon
    command: /usr/bin/supervisord
    env_file:
      - ./.env
    networks:
      - eth_net
    volumes:
      - ./files:/home/app/files
    logging:
      options:
        max-size: 100m


networks:
  eth_net:
    driver: bridge